ubuntuthin:
  client: fuji00
  image: ubuntuurunc
  numcpus: 1
  memory: 1024
  nets:
    - br0
  disks:
    - size: 20
  keys:
    - mydefaultkey.pub
  shutdown_flag: true

ubuntufat:
  client: fuji00
  image: ubuntuurunc
  numcpus: 2
  memory: 4096
  nets:
    - br0
  disks:
    - size: 30
  keys:
    - mydefaultkey.pub
  shutdown_flag: true
  
